### ISSUE TITLE
tests: implement OSS Fuzz

### ISSUE THREAD

**Issue by lukehinds** [stacklok/minder#174]
Once we OSS the code, we should introduce automated fuzzing:

https://github.com/google/oss-fuzz

**Comment by evankanderson** [comment]
Ada Logics will be doing some fuzzing, let's see where this is after the security audit.

**Comment by evankanderson** [comment]
Fixed by https://github.com/stacklok/minder/pull/3521 and the following tests added:

https://github.com/stacklok/minder/pull/3439
https://github.com/stacklok/minder/pull/3444
https://github.com/stacklok/minder/pull/3443
https://github.com/stacklok/minder/pull/3442
https://github.com/stacklok/minder/pull/3441
https://github.com/stacklok/minder/pull/3440
https://github.com/stacklok/minder/pull/3445
