### ISSUE TITLE
PR evaluator is /probably/ checking the wrong hash

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1991]
### Describe the issue

We use a magic comment in the PR that minder opens to check if a PR for this branch already exists. But when we force-push to the PR then the magic comment might not be invalid, but we don't update it.
We should either update the comment or rethink if we need it at all, since we are opening a PR from a branch could we check if the tip of the branch is the same as we created?

### To Reproduce

- Use the PR evaluator to open a PR
- cause the PR to be updated: e.g. open a PR that rolls out actions tags to SHAs in minder and then update one of the actions
- minder will keep pushing changes to the branch

**Comment by gregfurman** [comment]
Do you have any examples of this happening?

**Comment by jhrozek** [comment]
> Do you have any examples of this happening?

Hi Greg,
I think one of the PRs that triggered this issue was https://github.com/stacklok/minder/pull/1984. Unfortunately since the PR was merged, I don't see all the comments anymore, what I saw in the PR was that minder pushed the branch from one hash to another repeatedly.

 What I think was happening was that:

- this PR was opened
- another PR that bumped an action was opened by dependabot
- this triggered a rebase of the pin-actions PR which triggered the PR remediator to update the PR by pushing a new branch
- this branch didn't match the SHA we use in the magic comment, but since there was a PR opened from that branch already, no new PR was opened
- updating the PR triggered receiving a "push" webhook event from github
- this triggered the whole machinery again

I saw in one of your issue comments that you planned to update the review with the correct SHAs and I think this is exactly what we need to do in the PR code as well. Is either of those issues something you planned to work on or would you prefer us to fix them? (Neither of them is assigned, which is fine, just asking if I should put them into my work queue)

**Comment by gregfurman** [comment]
Hi Jacob. I am currently working on #1862 but have a local fix for the review issue that has now been closed at #1949 (the latter being closed in favour of the former).

I'll give a look at this PR evaluator problem too and see if it is caused by the same/similar issues and update this thread. 

The issue I found with the reviews was that we were assuming the API returned review data in order of latest to oldest (sorted by creation time). The reality is the exact opposite -- reviews are returned from earliest to latest. That meant we were incorrectly assigning an older object as the latest Minder review which in turn caused multiple reviews to be erroneously made.

I'm happy to push my changes for the review issue in #1949 however #1862 would mean just a single review is posted and repeatedly being edited -- which would effectively mitigate the problem of spamming comments. If we'd prefer an interim solution then I am happy with making a PR.

**Comment by jhrozek** [comment]
> Hi Jakub. I am currently working on #1862 but have a local fix for the review issue that has now been closed at #1949 (the latter being closed in favour of the former).
> 

Great!

> I'll give a look at this PR evaluator problem too and see if it is caused by the same/similar issues and update this thread.
> 

Sure, feel free to ping me on Discord if you need any pointers or explanation. I wrote parts of both files so it's likely that any mistakes are repeated. The file to look at for this bug would be probably pull_request.go

> The issue I found with the reviews was that we were assuming the API returned review data in order of latest to oldest (sorted by creation time). The reality is the exact opposite -- reviews are returned from earliest to latest. That meant we were incorrectly assigning an older object as the latest Minder review which in turn caused multiple reviews to be erroneously made.
> 

This was a really nice find!

> I'm happy to push my changes for the review issue in #1949 however #1862 would mean just a single review is posted and repeatedly being edited -- which would effectively mitigate the problem of spamming comments. If we'd prefer an interim solution then I am happy with making a PR.

As you wish, feel free to take your time and as I said earlier, feel free to also ping on Discord for any brainstorming.

**Comment by jhrozek** [comment]
Fixed in e8d41c1a96854c660ff59bb088bfd224b9db2d52
