### ISSUE TITLE
Update openfga to have the same roles for list repositories and reconcile (now it is editor & admin)

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#3794]
cc: @jhrozek

**Comment by jhrozek** [comment]
also cc @JAORMX - this is catching with us :-)

This is how a user would see the bug:
 - if a person is assigned the "editor" role and not "admin", they cannot list repos from the remote provider. But they can still click the "Manage repositories" button. Since there are no remote repositories to list, they cannot see the individual repos to add. But there is still the "Select repositories" dialog. And if they click the "All repositories" radio-button, the bug manifests
 - The "All repositories" button should add all future and current repos. But adding all future repos requires "admin" permissions which the user doesn't have. The problem is, adding all current repos (all currently allowed at github) is only an "editor" action.
 - Enabling future repos fails, adding current repos succeeds.
 
Technical details:
 - The ListRemoteRepositories RPC is currently admin only
 - The ReconcileEntitiesForRegistration is currently editor or admin
 - The code from ReconcileEntitiesForRegistration calls the code of ListRemoteRepositories internally

We should both put them on the same permission level, regardless of which it is.

cc @kantord @peppescg if you think this needs to be improved FE-side
