### ISSUE TITLE
Remove database access from GitHub webhook handler

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#4327]
### Please describe the enhancement

-

### Solution Proposal

-

**Comment by jhrozek** [comment]
Since the work breakdown we did initially was not great and it might have been a bit opaque what we did I'm going to break this issue into 2 - removing the database access from the GH provider was not strictly needed to enable github, but the generic entity lookup and evaluation enabled us to both implement the GL provider and make the GH provider use the same code. That part is now done and to make it clearer what was done and why I split that part of work into https://github.com/stacklok/minder/issues/4561

**Comment by jhrozek** [comment]
This was fixed by fixing #4618, #4619, #4621, #4666, #4667, #4682, #4703
