### ISSUE TITLE
Slow API response sandbox and connection closed due to slow provider instantiation

### ISSUE THREAD

**Issue by peppescg** [stacklok/minder#4391]
Trying to debug vercel preview env, but I got an issue on retrieving data from the APIs, it happens only in sandobx ( sometimes it is slow but it works).
In particular the `GET:api.sandbox.stacklok.dev/api/v1/results - 10.66s` seems to be very slow
```
GET:api.sandbox.stacklok.dev/api/v1/providers - 170ms
GET:api.sandbox.stacklok.dev/api/v1/user - 29ms
GET:api.sandbox.stacklok.dev/api/v1/user - 8ms
GET:api.sandbox.stacklok.dev/api/v1/repositories - 19ms
GET:api.sandbox.stacklok.dev/api/v1/providers - 93ms
GET:api.sandbox.stacklok.dev/api/v1/providers/github-app-peppescg - 92ms
GET:api.sandbox.stacklok.dev/api/v1/results - 10.66s
GET:api.sandbox.stacklok.dev/api/v1/profiles - 13ms
```

**Vercel logs:**
Vercel Runtime Timeout Error: Task timed out after 15 seconds

**Comment by jhrozek** [comment]
I did a bit of poor man's performance testing (time.Now and time.Since() pretty much) but that already showed that our database queries are quite fast. What's slow is instantiating the provider.

It turns out that instantiating a github-app provider does an upstream call (`appClient.Apps.CreateInstallationToken`) to get the token. And because we're looping over a slice of historical evaluations and instantiating the provider in every loop, we're doing an upstream call per historical evaluation. That part takes about 0.2s per entity on my machine (probably less in staging) which quickly adds up. I think this is also why you see the user or repositories endpoints to be very fast, but the provider related endpoints an order of magnitude slower - but at least they are doing one provider instantiation, whereas the historical evaluation does one per entity.

The offending path is:
```
providerManager -> providerClassManager -> Build -> getProviderCredentials -> NewGitHubInstallationTokenCredential -> createProviderWithAccessToken -> generateInstallationAccessToken
```

We should probably cache the provider instances. There is already the `restCache` being read from the the provider manager but I don't see the cache being written to..
